# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Obu_iJzG9T25t0svrTalbooFGAh0xCTO
"""

import json
import csv

INPUT_JSON = "eprom.json"
INPUT_CSV = "promotions.csv"
OUTPUT_FILE = "promotions_final.csv"

PROMOTIONS_ATTRIBUTES = {
    "promo_id": "promo_id",
    "promo_name": "promo_name",
    "promo_type": "promo_type",
    "discount_value": "discount_value",
    "min_order_value": "min_order_value",
    "applicable_category": "applicable_category",
    "promo_channel": "promo_channel",
    "stackable_flag": "stackable_flag",
    "start_date": "start_date",
    "end_date": "end_date",
}


def fill_promotion_attributes(raw_row):
    record = {}
    for attr, source_col in PROMOTIONS_ATTRIBUTES.items():
        record[attr] = raw_row.get(source_col)
    return record


def load_raw_records():
    with open(INPUT_JSON, "r", encoding="utf-8") as f:
        json_records = json.load(f)
    with open(INPUT_CSV, "r", encoding="utf-8") as f:
        csv_records = list(csv.DictReader(f))
    return json_records + csv_records


def main():
    raw_records = load_raw_records()
    promotion_records = [fill_promotion_attributes(r) for r in raw_records]

    with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(PROMOTIONS_ATTRIBUTES.keys()))
        writer.writeheader()
        writer.writerows(promotion_records)

    print(f"Da doc {len(raw_records)} dong, ghi ra {OUTPUT_FILE}")


if __name__ == "__main__":
    main()